kind: Secret
apiVersion: v1
metadata:
  name: gitlab-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodHRwczovL3JlZ2lzdHJ5LmdpdGxhYi5jb20iOnsKICAgICAgICAgICAgInVzZXJuYW1lIjoiZ2l0bGFiX3JlZ2lzdHJ5IiwKICAgICAgICAgICAgInRva2VuIjoicTRlUS02REQ5eVJ6aGJ3TTJpQlQiLAogICAgICAgICAgICAiYXV0aCI6IloybDBiR0ZpWDNKbFoybHpkSEo1T25FMFpWRXROa1JFT1hsU2VtaGlkMDB5YVVKVSIKICAgIAl9CiAgICB9Cn0K